name: CD

on:
  push:
    branches: master

jobs:
  build:
    runs-on: self-hosted
    env:
      PROFILE: prod
      PORT: 80
      HOMEPAGE: /
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ./gradlew build
      - name: deploy
        run: docker-compose up -d --build
